sudo: required

services:
  - docker

script:
  - docker --version
  - export VERSION=$(cat version)
  - export IMAGE_NAME=diunipisocc/toskose-unit
  - export VCS_REF=`git rev-parse --short HEAD`
  - export BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"`
  - |
    docker build \
    --build-arg VERSION=${VERSION} \
    --build-arg VCS_REF=${VCS_REF} \
    --build-arg BUILD_DATE=${BUILD_DATE} \
    -t $IMAGE_NAME:${VERSION} \
    -t $IMAGE_NAME:latest \
    .
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
  - docker push $IMAGE_NAME